version: 2
jobs:
  build:
    docker:
      - image: yutopp/rill-build-env:latest

    working_directory: /cibase

    steps:
      - checkout
      - run:
          name: build
          command: ./test/build.sh
      - run:
          name: test
          command: ./test/run.sh
      - run:
          name: coverage
          command: ./test/coverage.sh
      - store_artifacts:
          path: /artifacts
